### ISSUE TITLE
企业微信发送成功但是没有收到消息

### ISSUE THREAD

**Issue by telltime** [lyy910203/Alter#1]
![微信截图_20190812162928](https://user-images.githubusercontent.com/23161557/62853740-cc41a200-bd1f-11e9-9e6a-a34a12a80d36.png)

**Comment by telltime** [comment]
![yyyyyyyyyyyyy](https://user-images.githubusercontent.com/23161557/62854562-43783580-bd22-11e9-8a52-bea40c53a9c9.png)

**Comment by telltime** [comment]
test

**Comment by lyy910203** [comment]
您 的那些参数填写了嘛？
